### PR TITLE
remove dependency on 'six' transitional library

### PR DESCRIPTION
**Pull request by a-detiste**
Hi,

By adding annotations your project is certainly not compatible with Python2 anymore.

Please accept this PR to remove old remain of python2+3 compatibility

https://wiki.debian.org/Python3-six-removal

### CODE REVIEW

**Comment by langston-barrett** [comment]
Thanks @a-detiste!

**Comment by a-detiste** [comment]
I should help with this one too....  soonish

https://github.com/sphinx-contrib/autoprogram/issues/64

Le mar. 9 janv. 2024 à 16:18, Langston Barrett ***@***.***> a
écrit :

**Comment by a-detiste** [comment]
"This happens if the file is a script with no .py extension."

I've been trough this already once

https://github.com/systemd-cron/systemd-cron-python/blob/master/src/bin/crontab.py#L63

**Comment by langston-barrett** [comment]
I'm not sure I understand what you're referring to - can you elaborate?

**Comment by a-detiste** [comment]
This programs breaks with Python 3.12

The "imp" module is gone.

Code has to be rewritten python importlib.

**Pull request merged**
